// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadScanner returns the embedded CollectionSpec for Scanner.
func LoadScanner() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ScannerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Scanner: %w", err)
	}

	return spec, err
}

// LoadScannerObjects loads Scanner and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ScannerObjects
//	*ScannerPrograms
//	*ScannerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadScannerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadScanner()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ScannerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScannerSpecs struct {
	ScannerProgramSpecs
	ScannerMapSpecs
	ScannerVariableSpecs
}

// ScannerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScannerProgramSpecs struct {
	TracepointSchedProcessExit *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exit"`
	TracepointSchedProcessFork *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_fork"`
	TracepointSysEnterClone    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_clone"`
	TracepointSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_execve"`
	TracepointSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysEnterSocket   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_socket"`
	TracepointSysEnterUnlinkat *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_unlinkat"`
	TracepointSysEnterWrite    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_write"`
}

// ScannerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScannerMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// ScannerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScannerVariableSpecs struct {
}

// ScannerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadScannerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScannerObjects struct {
	ScannerPrograms
	ScannerMaps
	ScannerVariables
}

func (o *ScannerObjects) Close() error {
	return _ScannerClose(
		&o.ScannerPrograms,
		&o.ScannerMaps,
	)
}

// ScannerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadScannerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScannerMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *ScannerMaps) Close() error {
	return _ScannerClose(
		m.Events,
		m.TargetPids,
	)
}

// ScannerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadScannerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScannerVariables struct {
}

// ScannerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadScannerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScannerPrograms struct {
	TracepointSchedProcessExit *ebpf.Program `ebpf:"tracepoint_sched_process_exit"`
	TracepointSchedProcessFork *ebpf.Program `ebpf:"tracepoint_sched_process_fork"`
	TracepointSysEnterClone    *ebpf.Program `ebpf:"tracepoint_sys_enter_clone"`
	TracepointSysEnterConnect  *ebpf.Program `ebpf:"tracepoint_sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.Program `ebpf:"tracepoint_sys_enter_execve"`
	TracepointSysEnterOpenat   *ebpf.Program `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysEnterSocket   *ebpf.Program `ebpf:"tracepoint_sys_enter_socket"`
	TracepointSysEnterUnlinkat *ebpf.Program `ebpf:"tracepoint_sys_enter_unlinkat"`
	TracepointSysEnterWrite    *ebpf.Program `ebpf:"tracepoint_sys_enter_write"`
}

func (p *ScannerPrograms) Close() error {
	return _ScannerClose(
		p.TracepointSchedProcessExit,
		p.TracepointSchedProcessFork,
		p.TracepointSysEnterClone,
		p.TracepointSysEnterConnect,
		p.TracepointSysEnterExecve,
		p.TracepointSysEnterOpenat,
		p.TracepointSysEnterSocket,
		p.TracepointSysEnterUnlinkat,
		p.TracepointSysEnterWrite,
	)
}

func _ScannerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed scanner_x86_bpfel.o
var _ScannerBytes []byte
